site_name: Empacotamento no Debian
site_description: Documentação sobre empacotamento de pacotes no Debian para GCES.
site_author: GCES - UNB

theme:
  name: material
  language: pt-BR

nav:
  - Início: index.md
  - Checklist: checklist.md
  - Apresentação: apresentacao.md
  - Código de Conduta: codigoDeConduta.md
  - Licença: licenca.md
  - Contribuição: contribuicao.md
  - Onboarding: onBoarding.md
  - Privacidade: privacidade.md
  - Roadmap: roadmap.md
  - Termos de Uso: termos.md
  - Reuniões: reuniao.md
  - Diario de Bordo: diario.md
  - Novo Checklist: newChecklist.md
  - Pacotes:
      - Maria Clara: pacotes/mariaClara.md
      - Erick Santos: pacotes/erickSantos.md
      - Natalia Rodrigues: pacotes/nataliaRodrigues.md
  - Tutorial:
      - Standards: tutorial/tutorialStandard.md
      - Roadmap: tutorial/roadmap.md
      - Vesões: tutorial/tutorialVersion.md
      - Empacotamento: tutorial/tutorialEmpacotamento.md
      - Patches: tutorial/tutorialPatches.md
      - Upstream: tutorial/tutorialUpstream.md
      - Salsa: tutorial/tutorial-salsa-gitlab-ssh.md
      - Ambiente: tutorial/tutorial-configurando-ambiente.md
      - Tracker: tutorial/introducao_tracker.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
