site_name: Empacotamento no Debian
site_description: Documentação sobre empacotamento de pacotes no Debian para GCES.
site_author: GCES - UNB

theme:
  name: material
  language: pt-BR

nav:
  - Início: index.md
  - Checklist: checklist.md
  - Apresentação: apresentacao.md
  - Código de Conduta: codigoDeConduta.md
  - Licença: licenca.md
  - Contribuição: contribuicao.md
  - Onboarding: onBoarding.md
  - Privacidade: privacidade.md
  - Roadmap: roadmap.md
  - Termos de Uso: termos.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
